In [6]:
import pandas as pd
import numpy as np

In [7]:
"""
numpy.concatenate()
"""

x=[1,2,3]
y=[4,5,6]
z=[7,8,9]

print(np.concatenate([x,y,z])) #vstack(),hstack() 세로 가로
print(np.vstack([x,y,z]))

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
"""
pandas.concat()
"""

#simply concatenate the two series objects

ser1=pd.Series(['A','B','C'], index=[1,2,3])
ser2=pd.Series(['D','E','F'], index=[4,5,6])


print(pd.concat([ser1,ser2]))

1    A
2    B
3    C
4    D
5    E
6    F
dtype: object


In [9]:
#make_df():create a DataFrame object
def make_df(cols, ind):
    data={c:[str(c)+ str(i) for i in ind]
    for c in cols}
    
    return pd.DataFrame(data, ind)

In [10]:
#DataFrame example
print(make_df('ABC',[1,2]))

    A   B   C
1  A1  B1  C1
2  A2  B2  C2


In [12]:
#Concatenate the two DataFrame objects
df1=make_df('AB', [1,2])
df2=make_df('AB', [3,4])

print(df1,'\n')
print(df2,'\n')

print(pd.concat([df1,df2],axis=1)) #default axis is 0

    A   B
1  A1  B1
2  A2  B2 

    A   B
3  A3  B3
4  A4  B4 

     A    B    A    B
1   A1   B1  NaN  NaN
2   A2   B2  NaN  NaN
3  NaN  NaN   A3   B3
4  NaN  NaN   A4   B4


In [14]:
#Change the axis to 0

df3=make_df('AB',[0,1])
df4=make_df('CD',[0,1])

print(df3,'\n')
print(df3,'\n')

    A   B
0  A0  B0
1  A1  B1 

    A   B
0  A0  B0
1  A1  B1 



In [16]:
"""
concate() Features
"""

#case1 :Duplicate indlces

x=make_df('AB',[0,1])
y=make_df('AB',[2,3])

y.index=x.index #make duplicate indlces

print(x,'\n')
print(y,'\n')

print(pd.concat([x,y]))

    A   B
0  A0  B0
1  A1  B1 

    A   B
0  A2  B2
1  A3  B3 

    A   B
0  A0  B0
1  A1  B1
0  A2  B2
1  A3  B3


In [18]:
#Case 2 :Catching duplications as errors

try:
    pd.concat([x,y], verify_integrity=True)
except ValueError as e:
    print("ValueError",e)

ValueError Indexes have overlapping values: Int64Index([0, 1], dtype='int64')


In [20]:
#Case 3:Ignore the index:
#assign integer-based indices automatically

pd.concat([x,y],ignore_index=True)

A   B
0  A0  B0
1  A1  B1
2  A2  B2
3  A3  B3

In [21]:
#Case 4: ADDing multiindex keys(hierarchical indexing)

pd.concat([x,y], keys=['x','y'])

A   B
x 0  A0  B0
  1  A1  B1
y 0  A2  B2
  1  A3  B3

In [24]:
"""
concat():Join operation
"""
x=make_df('ABC',[1,2])
y=make_df('BCD',[3,4])

In [26]:
#default:outer join->union

print(x,'\n')
print(y,'\n')
print(pd.concat([x,y], join='outer'))

    A   B   C
1  A1  B1  C1
2  A2  B2  C2 

    B   C   D
3  B3  C3  D3
4  B4  C4  D4 

     A   B   C    D
1   A1  B1  C1  NaN
2   A2  B2  C2  NaN
3  NaN  B3  C3   D3
4  NaN  B4  C4   D4


In [29]:
#inner join->intersection

print(df5,'\n')
print(df6,'\n')
print(pd.concat([df5,df6],join='inner'))

NameError: name 'df5' is not defined

In [31]:
#append()

print(df1);print()
print(df1);print()
print(df1.append(df2))

    A   B
1  A1  B1
2  A2  B2

    A   B
1  A1  B1
2  A2  B2

    A   B
1  A1  B1
2  A2  B2
3  A3  B3
4  A4  B4


In [34]:
"""
Join operations
"""
#Prepare the two Data-Frame objects

df1=pd.DataFrame({"employee":['Bob','Jake','Lisa','Sue'],
         'group':['Accounting','Enginerring','Engineering','HR']})
df1=pd.DataFrame({"employee":['Lisa','Bob','Jake','Sue'],
         'hire_date':[2004,2008,2012,2014]})

print(df1,'\n')
print(df2)

  employee  hire_date
0     Lisa       2004
1      Bob       2008
2     Jake       2012
3      Sue       2014 

    A   B
3  A3  B3
4  A4  B4


In [37]:
#one-to-one joins

df3=pd.merge(df1,df2)
print(df3)

MergeError: No common columns to perform merge on. Merge options: left_on=None, right_on=None, left_index=False, right_index=False

In [39]:
#Many-to-one joins
df4=pd.DataFrame({'group':['Accounting','Engineering','HR'],
                 'supervisor':['Carly','Guido','Steve']})

print(df3,'\n')
print(df3,'\n')

print(pd.merge(df3,df4))

    A   B
0  A0  B0
1  A1  B1 

    A   B
0  A0  B0
1  A1  B1 



MergeError: No common columns to perform merge on. Merge options: left_on=None, right_on=None, left_index=False, right_index=False

In [43]:
#Many-to-many-joins

df5=pd.DataFrame({'group':['Accounting','Accounting',
                 'Engineering','Engineering'
                           'HR','HR'],
                'skills':['math''spreadsheets','coding',
                          'linux','spreadsheets','organizations'] })
print(df1,'\n')
print(df5,'\n')

print(pd.merge(df1,df5))


  employee  hire_date
0     Lisa       2004
1      Bob       2008
2     Jake       2012
3      Sue       2014 

           group            skills
0     Accounting  mathspreadsheets
1     Accounting            coding
2    Engineering             linux
3  EngineeringHR      spreadsheets
4             HR     organizations 



MergeError: No common columns to perform merge on. Merge options: left_on=None, right_on=None, left_index=False, right_index=False

In [45]:
"""
Specifying the merge key
"""
# 'on' argument:use a common column as merge key

print(df1,'\n')
print(df2,'\n')

df1['age']=pd.Series([20,42,37,25])
df2['age']=pd.Series([37,20,42,25])

print(df1,'\n')
print(df2,'\n')

print(pd.merge(df1,df2, on='employee'))

  employee  hire_date  age
0     Lisa       2004   20
1      Bob       2008   42
2     Jake       2012   37
3      Sue       2014   25 

    A   B   age
3  A3  B3  25.0
4  A4  B4   NaN 

  employee  hire_date  age
0     Lisa       2004   20
1      Bob       2008   42
2     Jake       2012   37
3      Sue       2014   25 

    A   B   age
3  A3  B3  25.0
4  A4  B4   NaN 



KeyError: 'employee'

In [46]:
#'left_on' and 'right_on'arguments:
#merge two datasets with different columns(e,g,employee and name)

df3=pd.DataFrame({'name':['Bob','Jake','Lisa','Sue'],
                 'salary':[70000,80000,120000,900000]})

print(df1,'\n')
print(df3,'\n')

pd.merge(df1,df3,left_on="employee",right_on="name")

  employee  hire_date  age
0     Lisa       2004   20
1      Bob       2008   42
2     Jake       2012   37
3      Sue       2014   25 

   name  salary
0   Bob   70000
1  Jake   80000
2  Lisa  120000
3   Sue  900000 



employee  hire_date  age  name  salary
0     Lisa       2004   20  Lisa  120000
1      Bob       2008   42   Bob   70000
2     Jake       2012   37  Jake   80000
3      Sue       2014   25   Sue  900000

In [48]:
#'Left_index" and 'right_index' arguments
#merge on and index('employee')

df1a=df1.set_index('employee')
df2a=df1.set_index('employee')

print(df1a,'\n\n',df2a)

pd.merge(df1a,df2a,left_index=True,right_index=True)

          hire_date  age
employee                
Lisa           2004   20
Bob            2008   42
Jake           2012   37
Sue            2014   25 

           hire_date  age
employee                
Lisa           2004   20
Bob            2008   42
Jake           2012   37
Sue            2014   25


hire_date_x  age_x  hire_date_y  age_y
employee                                        
Lisa             2004     20         2004     20
Bob              2008     42         2008     42
Jake             2012     37         2012     37
Sue              2014     25         2014     25

In [53]:
"""
Specifying the join method
"""

df6=pd.DataFrame({'name':['Peter','Paul','Mary'],
                 'food':['fish','beans','bread']},
                columns=['name','food'])

df7=pd.DataFrame({'name':['Mary','joseph'],
                 'drink':['wine','beer']},
                columns=['name','drink'])

print(df6,'\n')
print(df7)

    name   food
0  Peter   fish
1   Paul  beans
2   Mary  bread 

     name drink
0    Mary  wine
1  joseph  beer


In [55]:
# inner join(default)
pd.merge(df6,df7,how='inner')

name   food drink
0  Mary  bread  wine

In [57]:
#outer join
pd.merge(df6,df7,how='outer')

name   food drink
0   Peter   fish   NaN
1    Paul  beans   NaN
2    Mary  bread  wine
3  joseph    NaN  beer

In [59]:
#left join
pd.merge(df6,df7,how='left')

name   food drink
0  Peter   fish   NaN
1   Paul  beans   NaN
2   Mary  bread  wine

In [60]:
#right join
pd.merge(df6,df7,how='right')

name   food drink
0    Mary  bread  wine
1  joseph    NaN  beer