In [10]:
"""
Hello world!
"""
print("hello world!")

print(100)

pi=3.14159
print(pi)

introduce="My name is "
name = "Jeon jeong Hyun"
print(introduce + name)

hello world!
100
3.14159
My name is Jeon jeong Hyun


In [2]:
user_name="Jeon Jeong Hyun"
user_id=201655004
user_email="rkdltm79@naver.com"
is_student="Yes"
user_favorite="FootBall"

In [28]:
"""
Data Types:Integers
"""

chairs=6
Tv=2
desk=3
aircon=1
broken_desk=-1

In [29]:
"""
Data types:Real numbers
"""

win_probability=1.5
mycar_version=2.5
my_grade=3.5



In [30]:
"""
Strings
"""

favorite_person="ancelotti"
favorite_country="Canada"
favorite_football_club="Real Madrid"


In [32]:
"""
Plus-Equals Operations
"""

a=8
a+=2
print(a)

10


In [1]:
"""
Name Error
"""


my_school="Hsu"
print(my_school)


Hsu


In [7]:
is_tested=True
print(type(is_tested)) #변수가 어떤 데이터 타입인지를 알려주는 함수

a=3.14
print(type(a))

<class 'bool'>
<class 'float'>


In [10]:
#1
print("Yes"=='Yes')

#2
print((2>1)==(5<10))

#3
c='2'
d=2
print(c==d)

True
True
False


In [15]:
True or True


True

In [17]:
True or False


True

In [19]:
False or False


False

In [21]:
1<2 or 3<1


True

In [22]:
3<1 or 1>6


False

In [24]:
1==1 or 1<2

True

In [29]:
"""
conditional statements

"""

puppy="maltepoo"
age=1
is_yes=False

if puppy=="maltese":
    is_yes=True
    if age<3:
    print("말티즈 새끼예요")

elif puppy=="poodle":
    is_yes=True
    print("푸들맞아요")
    
    else:
        is_yes=True
        print
    
    
    
    print(is_yes)


IndentationError: expected an indented block (<ipython-input-29-27acc81a408d>, line 13)

In [2]:
"""
Exception Handling
"""
x=1

try:
    print(y)
    print(x)
except:
    print('[Error]')
    
    print("Continue")

[Error]
Continue


In [6]:
"""
List
"""

primes=[2,3,5,7,11,2]
print(primes)

empty_list=[]
print(empty_list)

[2, 3, 5, 7, 11, 2]
[]


In [10]:
"""
Multiple different data types
"""
mixed=['Jenny',1,1.4,True]
print(mixed)
list_of_list=[['a',1],['b',2]]

['Jenny', 1, 1.4, True]


In [12]:
"""
Zeor-Indexing
"""

names=['Roger','Rafael','Andy','Novak']
print(names[0]) #first data
print(names[1])
print(names[2])
print(names[3])

Roger
Rafael
Andy
Novak


In [4]:
"""
Negative indexing
"""
names=['Roger','Rafael','Andy','Novak']
print(names[-1])#Last data
print(names[-2])
print(names[-3])
print(names[-4])

Novak
Andy
Rafael
Roger


In [13]:
"""
List Slicing
"""
hsu_buildings=['만우관','장공관','필헌관','소통관','송암관','늦봄관','장준하통일관']
building_slice=hsu_buildings[1:4]#독립적인 객체
building_slice[0]='생활관'

print(building_slice)
print(hsu_buildings)#생활관을 0번으로 해도 원본 값 변화x
print(hsu_buildings)#전체 출력

['생활관', '필헌관', '소통관']
['만우관', '장공관', '필헌관', '소통관', '송암관', '늦봄관', '장준하통일관']
['만우관', '장공관', '필헌관', '소통관', '송암관', '늦봄관', '장준하통일관']


In [16]:
"""
Multi-dimensional Lists
"""
restaurants=[['해우리','한식','고s'],['짜장명가','중식','중화비빔밥'],['찌개동아리','한식','제육전골'],['맘스터치','양식','싸이버거']]
print(restaurants[1][2])

restaurants[0][2]='해우라면'#고s에서 해우라면으로 바뀜
print(restaurants[0])

중화비빔밥
['해우리', '한식', '해우라면']


In [20]:
"""
Adding Lists Together
"""

items_one=['cake','cookie','bread']
items_two=['biscuit','tart']

total_items=items_one+items_two
print(total_items)

['cake', 'cookie', 'bread', 'biscuit', 'tart']


In [29]:
"""
Useful Method for Lists
"""

#Len()
knapsack=[2,4,3,7,10]
size=len(knapsack)
print(size)

#count()
backpack=['pencil','pen','notebook','textbook','pen','highlighter','pen'] 
numPen=backpack.count('pen') #pen의 갯수

print(numPen)

#append()
orders=['daisies','periwinkle']
orders.append('tulips')

print(orders)

#insert()
store_line=['karla','Maxium','martin','isabella']
store_line.insert(2,'vikor')

print(store_line)

#sort()
numbers=[4,2,1,3]
numbers.sort()
print(numbers)

hsu_buildings=['만우관','장공관','필헌관','소통관','송암관','늦봄관','장준하통일관']
hsu_buildings.sort()

print(hsu_buildings)

5
3
['daisies', 'periwinkle', 'tulips']
['karla', 'Maxium', 'vikor', 'martin', 'isabella']
[1, 2, 3, 4]
['늦봄관', '만우관', '소통관', '송암관', '장공관', '장준하통일관', '필헌관']


In [5]:
"""
for Loops
"""

nums=[1,2,3,4,5]
for num in nums:
    print(num)
    
#range()
for i in range(4):
    print("warning")
    

1
2
3
4
5
warning
warning
warning
warning


In [10]:
"""
continue Keyword
"""

nums=[1,2,-1,4,-5,5,2,-9]
for num in nums:
    #if num is negative, we skip it.
    if num < 0:
        continue
    print(num)

1
2
4
5
2


In [12]:
"""
break Keyword
"""

game_plays=['stage1','stage2','stage3','gameover','stage4','stage5']
for play in game_plays:
     if play =='gameover':  
        print("game is over...")
        break
    print(play + " is complete.")
    

IndentationError: unindent does not match any outer indentation level (<tokenize>, line 10)

In [32]:
"""
List comprehension including conditions
"""

one_to_ten = [i+1 for i in range(10)]
print(one_to_ten)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [35]:
"""
List
"""
hotspurs=[['손흥민','A+'],['해리케인','F'],['은돔벨레','F'],['델레 알리','B'],['루카스 모우라','B+'],['에메르송','D']]

poors=[player[0] for player in hotspurs if player[1]=='F']#f인 플레이어 출력
print(poors)

['해리케인', '은돔벨레']


In [38]:
"""
Nested Loops
"""

one_to_nine=[i+1 for i in range(9)]

for i in one_to_nine:
    for j in one_to_nine:
        print("%d X %d =%d" %(i,j, i*j))


1 X 1 =1
1 X 2 =2
1 X 3 =3
1 X 4 =4
1 X 5 =5
1 X 6 =6
1 X 7 =7
1 X 8 =8
1 X 9 =9
2 X 1 =2
2 X 2 =4
2 X 3 =6
2 X 4 =8
2 X 5 =10
2 X 6 =12
2 X 7 =14
2 X 8 =16
2 X 9 =18
3 X 1 =3
3 X 2 =6
3 X 3 =9
3 X 4 =12
3 X 5 =15
3 X 6 =18
3 X 7 =21
3 X 8 =24
3 X 9 =27
4 X 1 =4
4 X 2 =8
4 X 3 =12
4 X 4 =16
4 X 5 =20
4 X 6 =24
4 X 7 =28
4 X 8 =32
4 X 9 =36
5 X 1 =5
5 X 2 =10
5 X 3 =15
5 X 4 =20
5 X 5 =25
5 X 6 =30
5 X 7 =35
5 X 8 =40
5 X 9 =45
6 X 1 =6
6 X 2 =12
6 X 3 =18
6 X 4 =24
6 X 5 =30
6 X 6 =36
6 X 7 =42
6 X 8 =48
6 X 9 =54
7 X 1 =7
7 X 2 =14
7 X 3 =21
7 X 4 =28
7 X 5 =35
7 X 6 =42
7 X 7 =49
7 X 8 =56
7 X 9 =63
8 X 1 =8
8 X 2 =16
8 X 3 =24
8 X 4 =32
8 X 5 =40
8 X 6 =48
8 X 7 =56
8 X 8 =64
8 X 9 =72
9 X 1 =9
9 X 2 =18
9 X 3 =27
9 X 4 =36
9 X 5 =45
9 X 6 =54
9 X 7 =63
9 X 8 =72
9 X 9 =81


In [13]:
x=1
y=1

while x <5:
    print("do something")
    x+=1

do something
do something
do something
do something


In [14]:
"""
Funcitons vs Method
"""

def my_function(x):
    return x+1
my_function(1)

y=3
result=my_function(y)
print(result)

x=1

class my_class:
    def my_method(self):
        return x+1
    
cls=my_class()
cls.my_method()

4


2

In [11]:
"""
Function Parameters
"""

def introduce_myself(name, birthyear, city):
    print("Hello everyone, my name is %s, i was born in %d, and i live in %s."\
          % (name, birthyear, city))
    
introduce_myself("jeong hyun", 1997, "osan")#argument

Hello everyone, my name is jeong hyun, i was born in 1997, and i live in osan.


In [23]:
"""
Return Keyword
"""

#Leap year = 윤년(2월 29일)
def check_leap_year(year):
    if year % 4 == 0:
        return "%s is a leap year." % (year)
    else:
        return "%s is not a leap year." % (year)

check_leap_year(2020)  

'2020 is a leap year.'

In [24]:
"""
Returning Multiple Values
"""

def square_point(x,y,z):
    x_squared=x**2
    y_squared=y**2
    z_squared=z**2
    return x_squared, y_squared, z_squared
three_squared, four_squared, five_squared=square_point(3,4,5)
print(three_squared, four_squared, five_squared)

9 16 25


In [28]:
"""
Global Variables
"""

a="Hello"

def prints_a():
    print(a)

prints_a()

Hello


In [35]:
"""
Local Variables  #원래 에러뜸
"""

def f1():
    b=3 #local var.
    print(b)
    
f1()
print(b)

3
2


In [1]:
"""
Keyword arguments and Default Values
"""

def findvolume(height, width, depth):
    print("height=%s"%(height))
    print("width=%s"%(width))
    print("depth=%s"%(depth))
    return height*width*depth
        
        #ex:height=1,w=2, d=3 바꿔도 됨
print(findvolume(width=2,height=1,depth=3))

height=1
width=2
depth=3
6


In [17]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [18]:
#Creating a numpy Array
lst=[1,2,3,4]

arr=np.array(lst)
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [19]:
#.data attribute
print(arr.dtype)
lst=[1.1,1.2,2.5] #소수
arr=np.array(lst)
print(arr.dtype)

a=np.array([1,1.4,"1.1,1.2,2.5"])
print(a.dtype)

int32
float64
<U32


In [20]:
"""
Size Comparison of ndarray and list objects
"""

from sys import getsizeof

lst=[1,2,3,4,5,6,7,8,9,10,11,12,13,14] #56->64, 8bytes증가
print(getsizeof(lst))

arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14]) #96->100, int:4bytes  
print(getsizeof(arr))  #14까지 입력하면 lst가 arr보다 큼

168
160


In [21]:
"""
Operation with numpy arrays
"""

prices=[30,25,40,20,20,35,50,35]
price_arr=np.array(prices)
#with a list
new_prices=[price-5 for price in prices]
print(new_prices)

#with a ndarray
price_arr-=5
print(prices_arr)

[25, 20, 35, 15, 15, 30, 45, 30]


NameError: name 'prices_arr' is not defined

In [22]:
#실습 시험점수처리

test_1=np.array([92,94,88,91,87])
test_2=np.array([79,100,86,93,91])
test_3=np.array([87,85,72,90,92])

test_3_fixed=test_3 + 2
print(test_3_fixed)

total_grade=test_1+test_2+test_3_fixed
print(total_grade)

final_grade=total_grade/3
print(final_grade)

student_scores=np.array([test_1, test_2, test_3_fixed])
print(student_scores.shape)

student_scores=np.array([test_1, test_2, test_3_fixed])
print(student_scores)

jeremy_test_2=student_scores[1,3]
print(jeremy_test_2)

manual_adwoa_test_1=np.array([student_scores[0,1],student_scores[0,2]])
print(manual_adwoa_test_1)

print(student_scores[:,4])
print(student_scores[:,-1])

[89 87 74 92 94]
[260 281 248 276 272]
[86.66666667 93.66666667 82.66666667 92.         90.66666667]
(3, 5)
[[ 92  94  88  91  87]
 [ 79 100  86  93  91]
 [ 89  87  74  92  94]]
93
[94 88]
[87 91 94]
[87 91 94]


In [23]:
"""
Logical Operatinos with Arrays
"""

#masking
a=np.array([10,2,2,4,5,3,9,8,9,7])
mask=a>5
print(mask)

#Select using Logical operations
selected=a[a>5]
print(selected)

#Combined Logical operations

selected=a[(a>5) | (a<4)]
print(selected)

selected=a[(a>3) & (a<8)]
print(selected)

[ True False False False False False  True  True  True  True]
[10  9  8  9  7]
[10  2  2  3  9  8  9  7]
[4 5 7]


In [25]:
import numpy as np

In [24]:
"""
Numpy Array Attributes
"""

#creating an array

print(np.arange(3))
print(np.arange(3,9))
print(np.arange(3,9,2))

[0 1 2]
[3 4 5 6 7 8]
[3 5 7]


In [26]:
#Random number generato 실행할떄마다 랜덤난수출력

np.random.seed(0) #재실행해도 똑같은 난수 출력
arr1=np.random.randint(10, size=(3,4,5)) #6입력하면 6개 나옴
print(arr1)

[[[5 0 3 3 7]
  [9 3 5 2 4]
  [7 6 8 8 1]
  [6 7 7 8 1]]

 [[5 9 8 9 4]
  [3 0 3 5 0]
  [2 3 8 1 3]
  [3 3 7 0 1]]

 [[9 9 0 4 7]
  [3 2 7 2 0]
  [0 4 5 5 6]
  [8 4 1 4 9]]]


In [33]:
#Attributes

np.random.seed(1)
arr=np.random.randint(10, size=(3,4))
print (arr)

print("arr.ndim=", arr.ndim)
print("arr.shape=", arr.shape)
print("arr.size=", arr.size)

print("arr.dtype=", arr.dtype)
print("arr.itemsize=", arr.itemsize)
print("arr.nbytes=", arr.nbytes) #getsizeof

[[5 8 9 5]
 [0 0 1 7]
 [6 9 2 4]]
arr.ndim= 2
arr.shape= (3, 4)
arr.size= 12
arr.dtype= int32
arr.itemsize= 4
arr.nbytes= 48


In [35]:
"""
Slicing
"""
arr=np.arange(10)
print(arr)

print(arr[3:7])
print(arr[:5])
print(arr[5:])
print(arr[::3])
print(arr[2:8:2])

[0 1 2 3 4 5 6 7 8 9]
[3 4 5 6]
[0 1 2 3 4]
[5 6 7 8 9]
[0 3 6 9]
[2 4 6]


In [27]:
# Multi-dimensional Subarrays

np.random.seed(2)
arr=np.random.randint(10, size=(6,8))
print(arr)

arr_sub=arr[:2,:2]
print(arr)

arr_sub[0,0]=99
print(arr_sub)

print(arr_sub)

[[8 8 6 2 8 7 2 1]
 [5 4 4 5 7 3 6 4]
 [3 7 6 1 3 5 8 4]
 [6 3 9 2 0 4 2 4]
 [1 7 8 2 9 8 7 1]
 [6 8 5 9 9 9 3 0]]
[[8 8 6 2 8 7 2 1]
 [5 4 4 5 7 3 6 4]
 [3 7 6 1 3 5 8 4]
 [6 3 9 2 0 4 2 4]
 [1 7 8 2 9 8 7 1]
 [6 8 5 9 9 9 3 0]]
[[99  8]
 [ 5  4]]
[[99  8]
 [ 5  4]]


In [28]:
"""
Subarrays as no-copy views
"""

np.random.seed(2)
arr=np.random.randint(10, size=(6,8))
print(arr)

arr_sub=arr[:2,:2].copy()
print(arr_sub)

arr_sub[0,0]=99
print(arr_sub)
print

[[8 8 6 2 8 7 2 1]
 [5 4 4 5 7 3 6 4]
 [3 7 6 1 3 5 8 4]
 [6 3 9 2 0 4 2 4]
 [1 7 8 2 9 8 7 1]
 [6 8 5 9 9 9 3 0]]
[[8 8]
 [5 4]]
[[99  8]
 [ 5  4]]


<function print>

In [43]:
"""
Reshpaing of Arrays
"""

arr=np.arange(1,10)
print(arr, '\n')

grid=arr.reshape(3,3)
print(grid, '\n')

[1 2 3 4 5 6 7 8 9] 

[[1 2 3]
 [4 5 6]
 [7 8 9]] 



In [29]:
"""
Array Concatenation
"""
#np.concatenate(), np.vstack(), np.hstack()

arr_1=np.array([[1,2,3],[1,2,3]])
arr_2=np.array([[4,5,6],[4,5,6]])
arr_3=np.array([[7,8,9],[7,8,9]])

arr_total=np.concatenate([arr_1, arr_2, arr_3], axis=1)
print(arr_total)

arr_total=np.vstack([arr_1, arr_2, arr_3])
print(arr_total)

arr_total=np.hstack([arr_1,arr_2, arr_3])
print(arr_total)

[[1 2 3 4 5 6 7 8 9]
 [1 2 3 4 5 6 7 8 9]]
[[1 2 3]
 [1 2 3]
 [4 5 6]
 [4 5 6]
 [7 8 9]
 [7 8 9]]
[[1 2 3 4 5 6 7 8 9]
 [1 2 3 4 5 6 7 8 9]]


In [30]:
"""
Array Splitting
"""

arr=[1,2,3,99,99,3,2,1]
print(arr, '\n')

arr_1, arr_2, arr_3=np.split(arr,[3,5])  #[4]
print(arr_1, arr_2, arr_3)

[1, 2, 3, 99, 99, 3, 2, 1] 

[1 2 3] [99 99] [3 2 1]


In [31]:
#pdf_6
import numpy as np

In [34]:
"""
Computing reciprocals in loops
"""

def compute_reciprocals(values):
    output=np.empty(len(values))
    for i in range(len(values)):
        output[i]=1.0/values[i]
        return output
    
    calues=np.random.randint(1,10,size=5)
    print(values)
    
    compute_reciprocals(values)

In [39]:
"""
comparison: loop vs ufuncs
"""

big_array=np.random.randint(1,100,size=1000000)

#Looping on a big array
%timeit compute_reciprocals(big_array)

#magic function(e.g %i)

10.4 µs ± 97.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [38]:
#vecotrized operation

%timeit 1/ big_array

2.07 ms ± 135 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [45]:
"""
numpy.ufunc
"""

np.random.seed(1)
arr1=np.random.randint(10, size=(5))
arr2=np.random.randint(10, size=(5))
print(arr1, arr2)

arr1=arr1-2
print(arr)

arr3=arr1+arr2
print(arr3)

arr4=np.random.randint(10, size=(3,5))
print(arr4)

arr5=arr4**2
print(arr5)

[5 8 9 5 0] [0 1 7 6 9]
[1, 2, 3, 99, 99, 3, 2, 1]
[ 3  7 14  9  7]
[[2 4 5 2 4]
 [2 4 7 7 9]
 [1 7 0 6 9]]
[[ 4 16 25  4 16]
 [ 4 16 49 49 81]
 [ 1 49  0 36 81]]


In [48]:
"""
Ufunc:Array Arithmetic
"""

#Basic arithmetic opertations on an array
x=np.arange(4)
print("x     =",x)
print("x+5=", x+5)
print("x-5=", x-5)
print("x*2=", x*2)
print("x/2=", x/2)
print("x**2=", x**2)

x     = [0 1 2 3]
x+5= [5 6 7 8]
x-5= [-5 -4 -3 -2]
x*2= [0 2 4 6]
x/2= [0.  0.5 1.  1.5]
x**2= [0 1 4 9]


In [50]:
"""
Ufunc ablsolute value
"""

x=np.array([-2,-1,0,1,2])
print(np.abs(x))

x=np.array([3-4j,4-3j,2+0j,0+1j])
print(np.abs(x))

[2 1 0 1 2]
[5. 5. 2. 1.]


In [53]:
"""
Ufunc:Trigonometric functions
"""

theta=np.linspace(0, np.pi, 3)

print(theta)

print(np.sin(theta))
print(np.cos(theta))
print(np.tan(theta))

[0.         1.57079633 3.14159265]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [56]:
"""
UFunc: Aggregation
"""

x=np.arange(1,5)
print(x)

aggr=np.add.reduce(x)
print(aggr)

#multiply
aggr=np.multiply.reduce(x)
print(aggr)

[1 2 3 4]
10
24


In [61]:
#accumulate()

x=np.arange(1,15)
print(x)

accum=np.add.accumulate(x)
print(accum)

accum=np.multiply.accumulate(x)
print(accum)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[  1   3   6  10  15  21  28  36  45  55  66  78  91 105]
[         1          2          6         24        120        720
       5040      40320     362880    3628800   39916800  479001600
 1932053504 1278945280]


In [66]:
#suming the calues in an array

np.random.seed(2)
arr=np.random.rand(100000) #rand(): create 0~1 real values

print(arr)
print('sum::=', np.sum(arr))

%timeit sum(arr)

[0.4359949  0.02592623 0.54966248 ... 0.42048616 0.30789564 0.87024385]
sum::= 49922.612009233395
7.89 ms ± 52.6 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [68]:
%timeit np.sum(arr)

30.2 µs ± 99.3 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [70]:
#other aggr. function
print("max=", np.max(arr))
print("min=", np.min(arr))
print("mean=", np.mean(arr))
print("median=", np.median(arr))
print("percentile=", np.percentile(arr,50))
print(np.any(arr>1))
print(np.all(arr>0))

max= 0.9999869419091001
min= 1.8354603294024052e-05
mean= 0.49922612009233397
median= 0.49893833891779144
percentile= 0.49893833891779144
False
True


In [74]:
#multi dimensional aggregates

np.random.seed(5)

arr=np.random.randint(10, size=(3,4))
print(arr)

print(np.sum(arr, axis=0)) #세로방향 계산
print(np.sum(arr, axis=1)) #세로방향 계산

[[3 6 6 0]
 [9 8 4 7]
 [0 0 7 1]]
[12 14 17  8]
[15 28  8]
