In [1]:
# 1. 기본 라이브러리 불러오기
import cv2 # computer vision
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# 코딩할 부분
# inp : gray image
# mask : odd(홀수)
def ImageConv(inp,mask):
    n = mask.shape[0]
    k = np.uint8((n-1)/2)
    h,w = inp.shape

    inp_pad = np.zeros((h+2*k, w+2*k))
    inp_pad[k:h+k,k:w+k] = inp

    out = np.zeros((h+2*k, w+2*k))
    for i in range(k,h+k):
        for j in range(k,w+k):
            temp = inp_pad[i-k:i+k+1,j-k:j+k+1] # i : 1, k = 1
            for x in range(0,n):
                for y in range(0,n):
                    out[i,j] += temp[x,y]*mask[x,y]
    out = out[k:h+k,k:w+k]
    return out

In [4]:
# 2. (numpy) 필터(mask) 생성하기 및 이미지 불러오기
mask = np.array([[2,0,1],[0,1,2],[1,0,2]])
inp = np.array([[1,2,3],[0,1,2],[3,0,1]])
out = ImageConv(inp,mask)
print(out)

[[ 16.  30. 130.]
 [  5. 323.  27.]
 [ 31.   5.  14.]]
